// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAiWoHxVTvz73vy4SdcLT4Y_EIuAXbOjg',
    appId: '1:199030336680:web:d3408b3674711dbdf8e69d',
    messagingSenderId: '199030336680',
    projectId: 'fir-flutter-project1',
    authDomain: 'fir-flutter-project1.firebaseapp.com',
    storageBucket: 'fir-flutter-project1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC5HUWADyu0U0XIc6l9lI2_s5lDoNExhg',
    appId: '1:199030336680:android:4d16cb7ed97da99ef8e69d',
    messagingSenderId: '199030336680',
    projectId: 'fir-flutter-project1',
    storageBucket: 'fir-flutter-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqltbz4QFWvXZbUTihEw3_HareXdCitI',
    appId: '1:199030336680:ios:9d13852df54e5d82f8e69d',
    messagingSenderId: '199030336680',
    projectId: 'fir-flutter-project1',
    storageBucket: 'fir-flutter-project1.appspot.com',
    iosClientId: '199030336680-j4dbjjht5440kri55jsgg315bise2v0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUi',
  );
}
